name: Sync with AtomGit

on:
  schedule:
    - cron: "0 0 * * 0" # 每周日午夜执行

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Clone AtomGit repository
        run: git clone https://atomgit.com/maicarons/isuerp.git

      - name: Copy files to GitHub repository
        run: |
          cp -R isuerp/* .
          git add .
          git commit -m "Sync with AtomGit"
          git remote add github-origin https://github.com/Maicarons/isuerp.git
          git push -f github-origin HEAD:master
